// Runner dos testes unitários do host (TDR-0004): registra as funções de
// teste dos *_test.cpp e devolve o nº de falhas como exit code.
#include "harness.h"

namespace tests {
void testBlitBateComOGoldenDoJs();
void testBlitRecusaArgumentosForaDoBuffer();
void testFormatFromString();
void testGcGenerationFromName();
void testGcTotalsSeparateGenerations();
void testPassTimingIgnoresSlotsBeyondUsed();
void testPassTimingSkipsInvalidPairs();
void testFormatToStringRoundtrip();
void testBc7Math();
void testAppendPerfLog();
void testDescribeCurrentException();
void testGameConfig();
void testSceneMirrorPropagaTransformDoPai();
void testSceneMirrorRecusaArvoreForaDeOrdem();
void testSceneMirrorCortaPeloFrustum();
void testSceneMirrorIgnoraIndiceForaDaCena();
void testSceneMirrorNaoRecalculaQuemNaoMudou();
void testSceneMirrorAppendNaoRealocaOBufferDoJs();
void testSceneMirrorSubarrayEntregueAntesSegueValido();
void testSceneMirrorAppendMantemPaiAntesDeFilho();
void testSceneMirrorEstouroDeCapacidadeRecusaSemRealocar();
void testSceneMirrorRemocaoNaoMexeNoIndiceDosOutros();
void testSceneMirrorRemocaoLevaASubarvoreInteira();
void testSceneMirrorReaproveitaSlotDeLapide();
void testSceneMirrorLadoDaSombraVemDoBuildEDoFrame();
void testShadowCasterIgnoraInvisivel();
void testMainCullVisibilidadeHerdada();
void testMainCullFrustumComMaiorEscala();
void testMainCullZDeOrdenacao();
void testMainCullPassaLuzEJsCull();
void testMainCullRecusaNoNaoReproduzivelAlcancavel();
void testMainCullFrustumCulledPorFrame();
void testMainCullSetBoundsTrocaAEsfera();
void testShadowCasterExigeAutoriaEMalha();
void testShadowCasterLimiarAngularNasBordas();
void testShadowCasterAplicaLimiarNaCena();
void testShadowCasterCortaPeloFrustumDaCascata();
void testShadowCasterUsaCentroDaEsferaNaoDaOrigem();
void testShadowCasterGuardaOVinculoComAGeometria();
void testShadowCasterSegueOVisibleDoFrame();
void testShadowCasterSegueOMaterialVisibleDoFrame();
void testShadowCasterMaterialInicialVemDoBuild();
void testShadowGateAceitaCenaLimpa();
void testShadowGateRecusaSkinnedEInstanced();
void testShadowGateRecusaMaterialEmArray();
void testShadowGateRecusaRecorteAlfaEPositionNode();
void testShadowGateRecusaGeometriaAusenteDoRegistro();
void testShadowGateRecusaSemRegistroNenhum();
void testShadowGateRecusaDivergenciaDeNos();
void testShadowGateRecusaDivergenciaSemCasterNenhum();
void testShadowGateRecusaVsm();
void testShadowGatePrioridadeEContagemPorMotivo();
void testShadowGateMotivoTemNome();
void testShadowGateAceitaInstancedComMatrizesNoHost();
void testShadowGateRelataPrimeiroOfensor();
void testShadowGateAceitaOsTresLadosDaTabela();
void testShadowGateRecusaLadoNaoReproduzivel();
void testShadowGateVeOLadoQueChegouNoFrame();
void testShadowMvpIdentidade();
void testShadowMvpOrdemImporta();
void testShadowMvpPontoConhecido();
void testShadowMvpMantemPrecisaoDeCidade();
void testShadowCullSegueATabelaDoThree();
void testShadowCullNaoAproximaLadoDesconhecido();
void testShadowCullSegueOEspelhamentoDaMatriz();
void testShadowDeterminanteIgnoraATranslacao();
void testPipelineCacheCriaUmaVezPorChave();
void testPipelineCacheSeparaChavesDiferentes();
void testPipelineCacheNaoCriaNadaEmRegime();
void testPipelineCacheClearEsqueceTudo();
void testGeometryRegistry();
}  // namespace tests

int main() {
  tests::testFormatFromString();
  tests::testFormatToStringRoundtrip();
  tests::testBc7Math();
  tests::testAppendPerfLog();
  tests::testDescribeCurrentException();
  tests::testGameConfig();
  tests::testSceneMirrorPropagaTransformDoPai();
  tests::testSceneMirrorRecusaArvoreForaDeOrdem();
  tests::testSceneMirrorCortaPeloFrustum();
  tests::testSceneMirrorIgnoraIndiceForaDaCena();
  tests::testSceneMirrorNaoRecalculaQuemNaoMudou();
  tests::testSceneMirrorAppendNaoRealocaOBufferDoJs();
  tests::testSceneMirrorSubarrayEntregueAntesSegueValido();
  tests::testSceneMirrorAppendMantemPaiAntesDeFilho();
  tests::testSceneMirrorEstouroDeCapacidadeRecusaSemRealocar();
  tests::testSceneMirrorRemocaoNaoMexeNoIndiceDosOutros();
  tests::testSceneMirrorRemocaoLevaASubarvoreInteira();
  tests::testSceneMirrorReaproveitaSlotDeLapide();
  tests::testSceneMirrorLadoDaSombraVemDoBuildEDoFrame();
  tests::testShadowCasterIgnoraInvisivel();
  tests::testMainCullVisibilidadeHerdada();
  tests::testMainCullFrustumComMaiorEscala();
  tests::testMainCullZDeOrdenacao();
  tests::testMainCullPassaLuzEJsCull();
  tests::testMainCullRecusaNoNaoReproduzivelAlcancavel();
  tests::testMainCullFrustumCulledPorFrame();
  tests::testMainCullSetBoundsTrocaAEsfera();
  tests::testShadowCasterExigeAutoriaEMalha();
  tests::testShadowCasterLimiarAngularNasBordas();
  tests::testShadowCasterAplicaLimiarNaCena();
  tests::testShadowCasterCortaPeloFrustumDaCascata();
  tests::testShadowCasterUsaCentroDaEsferaNaoDaOrigem();
  tests::testShadowCasterGuardaOVinculoComAGeometria();
  tests::testShadowCasterSegueOVisibleDoFrame();
  tests::testShadowCasterSegueOMaterialVisibleDoFrame();
  tests::testShadowCasterMaterialInicialVemDoBuild();
  tests::testShadowGateAceitaCenaLimpa();
  tests::testShadowGateRecusaSkinnedEInstanced();
  tests::testShadowGateRecusaMaterialEmArray();
  tests::testShadowGateRecusaRecorteAlfaEPositionNode();
  tests::testShadowGateRecusaGeometriaAusenteDoRegistro();
  tests::testShadowGateRecusaSemRegistroNenhum();
  tests::testShadowGateRecusaDivergenciaDeNos();
  tests::testShadowGateRecusaDivergenciaSemCasterNenhum();
  tests::testShadowGateRecusaVsm();
  tests::testShadowGatePrioridadeEContagemPorMotivo();
  tests::testShadowGateMotivoTemNome();
  tests::testShadowGateAceitaInstancedComMatrizesNoHost();
  tests::testShadowGateRelataPrimeiroOfensor();
  tests::testShadowGateAceitaOsTresLadosDaTabela();
  tests::testShadowGateRecusaLadoNaoReproduzivel();
  tests::testShadowGateVeOLadoQueChegouNoFrame();
  tests::testShadowMvpIdentidade();
  tests::testShadowMvpOrdemImporta();
  tests::testShadowMvpPontoConhecido();
  tests::testShadowMvpMantemPrecisaoDeCidade();
  tests::testShadowCullSegueATabelaDoThree();
  tests::testShadowCullNaoAproximaLadoDesconhecido();
  tests::testShadowCullSegueOEspelhamentoDaMatriz();
  tests::testShadowDeterminanteIgnoraATranslacao();
  tests::testPipelineCacheCriaUmaVezPorChave();
  tests::testPipelineCacheSeparaChavesDiferentes();
  tests::testPipelineCacheNaoCriaNadaEmRegime();
  tests::testPipelineCacheClearEsqueceTudo();
  tests::testGeometryRegistry();
  tests::testGcGenerationFromName();
  tests::testGcTotalsSeparateGenerations();
  tests::testPassTimingIgnoresSlotsBeyondUsed();
  tests::testPassTimingSkipsInvalidPairs();
  tests::testBlitBateComOGoldenDoJs();
  tests::testBlitRecusaArgumentosForaDoBuffer();
  return testing::summary();
}
