// Runner dos testes unitários do host (TDR-0004): registra as funções de
// teste dos *_test.cpp e devolve o nº de falhas como exit code.
#include "harness.h"

namespace tests {
void testFormatFromString();
void testFormatToStringRoundtrip();
void testBc7Math();
void testAppendPerfLog();
void testDescribeCurrentException();
void testGameConfig();
void testSceneMirrorPropagaTransformDoPai();
void testSceneMirrorRecusaArvoreForaDeOrdem();
void testSceneMirrorCortaPeloFrustum();
void testSceneMirrorIgnoraIndiceForaDaCena();
void testSceneMirrorNaoRecalculaQuemNaoMudou();
void testSceneMirrorAppendNaoRealocaOBufferDoJs();
void testSceneMirrorSubarrayEntregueAntesSegueValido();
void testSceneMirrorAppendMantemPaiAntesDeFilho();
void testSceneMirrorEstouroDeCapacidadeRecusaSemRealocar();
void testSceneMirrorRemocaoNaoMexeNoIndiceDosOutros();
void testSceneMirrorRemocaoLevaASubarvoreInteira();
void testSceneMirrorReaproveitaSlotDeLapide();
void testShadowCasterIgnoraInvisivel();
void testShadowCasterExigeAutoriaEMalha();
void testShadowCasterLimiarAngularNasBordas();
void testShadowCasterAplicaLimiarNaCena();
void testShadowCasterCortaPeloFrustumDaCascata();
void testShadowCasterUsaCentroDaEsferaNaoDaOrigem();
void testShadowCasterGuardaOVinculoComAGeometria();
void testShadowCasterSegueOVisibleDoFrame();
void testShadowCasterSegueOMaterialVisibleDoFrame();
void testShadowCasterMaterialInicialVemDoBuild();
void testShadowGateAceitaCenaLimpa();
void testShadowGateRecusaSkinnedEInstanced();
void testShadowGateRecusaMaterialEmArray();
void testShadowGateRecusaRecorteAlfaEPositionNode();
void testShadowGateRecusaGeometriaAusenteDoRegistro();
void testShadowGateRecusaSemRegistroNenhum();
void testShadowGateRecusaDivergenciaDeNos();
void testShadowGateRecusaDivergenciaSemCasterNenhum();
void testShadowGateRecusaVsm();
void testShadowGatePrioridadeEContagemPorMotivo();
void testShadowGateMotivoTemNome();
void testShadowMvpIdentidade();
void testShadowMvpOrdemImporta();
void testShadowMvpPontoConhecido();
void testShadowMvpMantemPrecisaoDeCidade();
void testPipelineCacheCriaUmaVezPorChave();
void testPipelineCacheSeparaChavesDiferentes();
void testPipelineCacheNaoCriaNadaEmRegime();
void testPipelineCacheClearEsqueceTudo();
void testGeometryRegistry();
}  // namespace tests

int main() {
  tests::testFormatFromString();
  tests::testFormatToStringRoundtrip();
  tests::testBc7Math();
  tests::testAppendPerfLog();
  tests::testDescribeCurrentException();
  tests::testGameConfig();
  tests::testSceneMirrorPropagaTransformDoPai();
  tests::testSceneMirrorRecusaArvoreForaDeOrdem();
  tests::testSceneMirrorCortaPeloFrustum();
  tests::testSceneMirrorIgnoraIndiceForaDaCena();
  tests::testSceneMirrorNaoRecalculaQuemNaoMudou();
  tests::testSceneMirrorAppendNaoRealocaOBufferDoJs();
  tests::testSceneMirrorSubarrayEntregueAntesSegueValido();
  tests::testSceneMirrorAppendMantemPaiAntesDeFilho();
  tests::testSceneMirrorEstouroDeCapacidadeRecusaSemRealocar();
  tests::testSceneMirrorRemocaoNaoMexeNoIndiceDosOutros();
  tests::testSceneMirrorRemocaoLevaASubarvoreInteira();
  tests::testSceneMirrorReaproveitaSlotDeLapide();
  tests::testShadowCasterIgnoraInvisivel();
  tests::testShadowCasterExigeAutoriaEMalha();
  tests::testShadowCasterLimiarAngularNasBordas();
  tests::testShadowCasterAplicaLimiarNaCena();
  tests::testShadowCasterCortaPeloFrustumDaCascata();
  tests::testShadowCasterUsaCentroDaEsferaNaoDaOrigem();
  tests::testShadowCasterGuardaOVinculoComAGeometria();
  tests::testShadowCasterSegueOVisibleDoFrame();
  tests::testShadowCasterSegueOMaterialVisibleDoFrame();
  tests::testShadowCasterMaterialInicialVemDoBuild();
  tests::testShadowGateAceitaCenaLimpa();
  tests::testShadowGateRecusaSkinnedEInstanced();
  tests::testShadowGateRecusaMaterialEmArray();
  tests::testShadowGateRecusaRecorteAlfaEPositionNode();
  tests::testShadowGateRecusaGeometriaAusenteDoRegistro();
  tests::testShadowGateRecusaSemRegistroNenhum();
  tests::testShadowGateRecusaDivergenciaDeNos();
  tests::testShadowGateRecusaDivergenciaSemCasterNenhum();
  tests::testShadowGateRecusaVsm();
  tests::testShadowGatePrioridadeEContagemPorMotivo();
  tests::testShadowGateMotivoTemNome();
  tests::testShadowMvpIdentidade();
  tests::testShadowMvpOrdemImporta();
  tests::testShadowMvpPontoConhecido();
  tests::testShadowMvpMantemPrecisaoDeCidade();
  tests::testPipelineCacheCriaUmaVezPorChave();
  tests::testPipelineCacheSeparaChavesDiferentes();
  tests::testPipelineCacheNaoCriaNadaEmRegime();
  tests::testPipelineCacheClearEsqueceTudo();
  tests::testGeometryRegistry();
  return testing::summary();
}
